#if !defined(AFX_DATASOURCE_H__C7E98546_2347_11D2_AEFB_00A0C9B71DC4__INCLUDED_)
#define AFX_DATASOURCE_H__C7E98546_2347_11D2_AEFB_00A0C9B71DC4__INCLUDED_

#if _MSC_VER >= 1000
#pragma once
#endif // _MSC_VER >= 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDataSource wrapper class

class CDataSource : public CWnd
{
protected:
	DECLARE_DYNCREATE(CDataSource)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x7ca41f77, 0x91c, 0x11d2, { 0xae, 0xe6, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	CString AccessSync(BSTR* command);
	CString AccessOutput(BSTR* query);
	BOOL IsConnectionLost();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATASOURCE_H__C7E98546_2347_11D2_AEFB_00A0C9B71DC4__INCLUDED_)
