//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cbrowserframe.rc
//
#define IDS_CBROWSERFRAME               1
#define IDD_ABOUTBOX_CBROWSERFRAME      1
#define IDB_CBROWSERFRAME               1
#define IDI_ABOUTDLL                    1
#define IDB_BROWSERFRAME                1
#define IDS_BROWSERFRAME                1
#define IDS_CBROWSERFRAME_PPG           2
#define ID_APPLY                        3
#define IDS_CBROWSERFRAME_PPG_CAPTION   100
#define IDD_PROPPAGE_CBROWSERFRAME      100
#define IDS_STRING101                   101
#define IDS_INFO                        102
#define IDD_ADDTPM                      144
#define IDD_NEWFILTER                   145
#define IDD_GROUPSVIEW                  201
#define IDD_SUBSYSVIEW                  203
#define IDC_SUBSYSTEMS                  203
#define IDC_DATASOURCE                  204
#define IDD_SUBSYSCREATE                205
#define IDB_ARROWRIGHT                  206
#define IDC_GROUPS                      206
#define IDD_TPMMATCH                    206
#define IDB_ARROWLEFT                   207
#define IDC_NEW                         207
#define IDC_EDIT                        209
#define IDC_TPMPROP                     210
#define IDB_AND                         211
#define IDC_TPMSEL                      211
#define IDB_OR                          212
#define IDB_FILTERLIST                  213
#define IDC_INCLUSIVE                   213
#define IDB_FILTERWIZARD                216
#define IDB_ARROWUP                     218
#define IDB_ARROWDN                     219
#define IDD_ATTRIBUTES                  300
#define IDD_FILTER                      305
#define IDD_FILTERLIST                  310
#define IDD_SORT                        315
#define IDD_FILTERWIZARD                320
#define IDS_NAME_COLUMN                 501
#define IDS_FILE_COLUMN                 502
#define IDS_EXTENTION_COLUMN            503
#define IDS_LINE_COLUMN                 504
#define IDS_TYPE_COLUMN                 505
#define IDS_ARGNUM_COLUMN               506
#define IDS_ARGS_COLUMN                 507
#define IDS_KIND_COLUMN                 508
#define IDS_LANGUAGE_COLUMN             509
#define IDS_MODELFILE_COLUMN            510
#define IDS_CYCLCOMPLEXITY_COLUMN       511
#define IDS_MYERCOMPLEXITY_COLUMN       512
#define IDS_SUPERCLASSES_COLUMN         513
#define IDS_SUBCLASSES_COLUMN           514
#define IDS_SIZE_COLUMN                 515
#define IDS_DEPTH_COLUMN                516
#define IDS_DANGLINGELSEIF_COLUMN       517
#define IDS_DEFLESSSWITCH_COLUMN        518
#define IDS_START_COLUMN                519
#define IDS_RETURN_COLUMN               520
#define IDS_LINESAMOUNT_COLUMN          521
#define IDS_UNCOMMENTAMOUNT_COLUMN      522
#define IDS_EXECUTABLEAMOUNT_COLUMN     523
#define IDS_IFSAMOUNT_COLUMN            524
#define IDS_LOOPSAMOUNT_COLUMN          525
#define IDS_SWITCHESAMOUNT_COLUMN       526
#define IDS_DEFAULTAMOUNT_COLUMN        527
#define IDS_STATUS_COLUMN               528
#define IDS_NAME_COMMAND                601
#define IDS_FILE_COMMAND                602
#define IDS_EXTENTION_COMMAND           603
#define IDS_LINE_COMMAND                604
#define IDS_TYPE_COMMAND                605
#define IDS_ARGNUM_COMMAND              606
#define IDS_ARGS_COMMAND                607
#define IDS_KIND_COMMAND                608
#define IDS_LANGUAGE_COMMAND            609
#define IDS_MODELFILE_COMMAND           610
#define IDS_CYCLCOMPLEXITY_COMMAND      611
#define IDS_MYERCOMPLEXITY_COMMAND      612
#define IDS_SUPERCLASSES_COMMAND        613
#define IDS_SUBCLASSES_COMMAND          614
#define IDS_SIZE_COMMAND                615
#define IDS_DEPTH_COMMAND               616
#define IDS_DANGLINGELSEIF_COMMAND      617
#define IDS_DEFLESSSWITCH_COMMAND       618
#define IDS_START_COMMAND               619
#define IDS_RETURN_COMMAND              620
#define IDS_LINESAMOUNT_COMMAND         621
#define IDS_UNCOMMENTAMOUNT_COMMAND     622
#define IDS_EXECUTABLEAMOUNT_COMMAND    623
#define IDS_IFSAMOUNT_COMMAND           624
#define IDS_LOOPSAMOUNT_COMMAND         625
#define IDS_SWITCHESAMOUNT_COMMAND      626
#define IDS_DEFAULTAMOUNT_COMMAND       627
#define IDS_STATUS_COMMAND              628
#define IDS_NAME_TYPE                   701
#define IDS_FILE_TYPE                   702
#define IDS_EXTENTION_TYPE              703
#define IDS_LINE_TYPE                   704
#define IDS_TYPE_TYPE                   705
#define IDS_ARGNUM_TYPE                 706
#define IDS_ARGS_TYPE                   707
#define IDS_KIND_TYPE                   708
#define IDS_LANGUAGE_TYPE               709
#define IDS_MODELFILE_TYPE              710
#define IDS_CYCLCOMPLEXITY_TYPE         711
#define IDS_MYERCOMPLEXITY_TYPE         712
#define IDS_SUPERCLASSES_TYPE           713
#define IDS_SUBCLASSES_TYPE             714
#define IDS_SIZE_TYPE                   715
#define IDS_DEPTH_TYPE                  716
#define IDS_DANGLINGELSEIF_TYPE         717
#define IDS_DEFLESSSWITCH_TYPE          718
#define IDS_START_TYPE                  719
#define IDS_RETURN_TYPE                 720
#define IDS_LINESAMOUNT_TYPE            721
#define IDS_UNCOMMENTAMOUNT_TYPE        722
#define IDS_EXECUTABLEAMOUNT_TYPE       723
#define IDS_IFSAMOUNT_TYPE              724
#define IDS_LOOPSAMOUNT_TYPE            725
#define IDS_SWITCHESAMOUNT_TYPE         726
#define IDS_DEFAULTAMOUNT_TYPE          727
#define IDS_STATUS_TYPE                 728
#define IDS_FIELDMESSAGE                729
#define IDS_FIELDCAPTION                730
#define IDS_OP_INT                      800
#define IDS_OP_INT2                     801
#define IDS_OP_INT3                     802
#define IDS_OP_INT4                     803
#define IDS_OP_INT5                     804
#define IDS_OP_INT6                     805
#define IDS_OP_STR                      806
#define IDS_OP_STR2                     807
#define IDS_OP_STR3                     808
#define IDS_OP_STR4                     809
#define IDS_OP_STR5                     810
#define IDS_FMT_INT                     811
#define IDS_FMT_INT2                    812
#define IDS_FMT_INT3                    813
#define IDS_FMT_INT4                    814
#define IDS_FMT_INT5                    815
#define IDS_FMT_INT6                    816
#define IDS_FMT_STR                     817
#define IDS_FMT_STR2                    818
#define IDS_FMT_STR3                    819
#define IDS_FMT_STR4                    820
#define IDS_FMT_STR5                    821
#define IDAPPLY                         1000
#define IDC_ARGUMENT                    1005
#define IDC_SELATTRIBUTES               1010
#define IDC_SOURCEATTR                  1015
#define IDC_DESTATTR                    1020
#define IDC_ONE_TO_SOURCE               1025
#define IDC_ONE_TO_DEST                 1030
#define IDC_OPERATION                   1035
#define IDC_TABEXPRESSION               1040
#define IDC_CURRENTEDIT                 1044
#define IDC_OR                          1045
#define IDC_NEWEDIT                     1046
#define IDC_COMMENTEDIT                 1047
#define IDC_FROMSELECTION               1048
#define IDC_CHANGE                      1049
#define IDC_AND                         1050
#define IDC_FILTEREDIT                  1050
#define IDC_EDITEXPRESSION              1055
#define IDC_ATTRIBUTE                   1060
#define IDC_ADDBUTTON                   1065
#define IDC_REMOVEBUTTON                1070
#define IDC_CHANGEBUTTON                1075
#define IDC_SAVELIST                    1080
#define IDC_NAMEEDIT                    1085
#define IDC_COMMANDEDIT                 1090
#define IDC_SOURCE                      1095
#define IDC_DESTINATION                 1100
#define IDC_ADD                         1105
#define IDC_REMOVE                      1110
#define IDC_DECENDING                   1115
#define IDC_ACENDING                    1120
#define IDC_SELECTFILTER                1125
#define IDC_RESETFILTER                 1130
#define IDC_SELECTSORT                  1135
#define IDC_ADDELEMENTS                 1137

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        209
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         217
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
