default:
	$(MAKE) -C ../../ -f new-rules/make-one-prog.mk \
	PROG=discover/if_diff/src/prog.mk

clean:
	$(MAKE) -C ../../ -f new-rules/make-one-prog.mk \
	PROG=discover/if_diff/src/prog.mk \
	clean

include ../../new-rules/new-testsuite.mk
