#!/bin/sh

tmpfile=$1
cat $tmpfile | while read cm_workfile
do	
  read cm_sysfile

  if [ -f $cm_workfile -a "$cm_workfile" != "$cm_sysfile" ] ; then
    echo "rm -f $cm_sysfile;cp $cm_workfile $cm_sysfile;rm -f $cm_workfile"
    rm -f $cm_sysfile
    cp $cm_workfile $cm_sysfile
    rm -f $cm_workfile
  fi 

done

exit 0
