/*************************************************************************
* Copyright (c) 2015, Synopsys, Inc.                                     *
* All rights reserved.                                                   *
*                                                                        *
* Redistribution and use in source and binary forms, with or without     *
* modification, are permitted provided that the following conditions are *
* met:                                                                   *
*                                                                        *
* 1. Redistributions of source code must retain the above copyright      *
* notice, this list of conditions and the following disclaimer.          *
*                                                                        *
* 2. Redistributions in binary form must reproduce the above copyright   *
* notice, this list of conditions and the following disclaimer in the    *
* documentation and/or other materials provided with the distribution.   *
*                                                                        *
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS    *
* "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT      *
* LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR  *
* A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT   *
* HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, *
* SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT       *
* LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,  *
* DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY  *
* THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT    *
* (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE  *
* OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   *
*************************************************************************/
   { "%FOUND", Y_PCT_FOUND },
   { "%ISOPEN", Y_PCT_ISOPEN },
   { "%NOTFOUND", Y_PCT_NOTFOUND },
   { "%ROWCOUNT", Y_PCT_ROWCOUNT },
   { "%ROWTYPE", Y_PCT_ROWTYPE },
   { "%TYPE", Y_PCT_TYPE },
   { "AFTER", Y_AFTER },
   { "ALL", Y_ALL },
   { "AND", Y_AND },
   { "ANY", Y_ANY },
   { "AS", Y_AS },
   { "ASC", Y_ASC },
   { "AUTHORIZATION", Y_AUTHORIZATION },
   { "AVG", Y_AVG },
   { "BEFORE", Y_BEFORE },
   { "BEGIN", Y_BEGIN },
   { "BETWEEN", Y_BETWEEN },
   { "BINARY_INTEGER", Y_BINARY_INTEGER },
   { "BODY", Y_BODY },
   { "BOOLEAN", Y_BOOLEAN },
   { "BY", Y_BY },
   { "CACHE", Y_CACHE },
   { "CASCADE", Y_CASCADE },
   { "CHAR", Y_CHAR },
   { "CHARACTER", Y_CHARACTER },
   { "CHECK", Y_CHECK },
   { "CLOSE", Y_CLOSE },
   { "COMMENT", Y_COMMENT },
   { "COMMIT", Y_COMMIT },
   { "COMMITTED", Y_COMMITTED },
   { "CONNECT", Y_CONNECT },
   { "CONSTANT", Y_CONSTANT },
   { "CONSTRAINT", Y_CONSTRAINT },
   { "CONSTRAINTS", Y_CONSTRAINTS },
   { "COUNT", Y_COUNT },
   { "CREATE", Y_CREATE },
   { "CURRENT", Y_CURRENT },
   { "CURRVAL", Y_CURRVAL },
   { "CURSOR", Y_CURSOR },
   { "CYCLE", Y_CYCLE },
   { "DATE", Y_DATE },
   { "DEC", Y_DEC },
   { "DECIMAL", Y_DECIMAL },
   { "DECLARE", Y_DECLARE },
   { "DEFAULT", Y_DEFAULT },
   { "DELETE", Y_DELETE },
   { "DELETING", Y_DELETING },
   { "DESC", Y_DESC },
   { "DISTINCT", Y_DISTINCT },
   { "DOUBLE", Y_DOUBLE },
   { "DROP", Y_DROP },
   { "EACH", Y_EACH },
   { "ELSE", Y_ELSE },
   { "ELSIF", Y_ELSIF },
   { "END", Y_END },
   { "ESCAPE", Y_ESCAPE },
   { "EXCEPTION", Y_EXCEPTION },
   { "EXCEPTION_INIT", Y_EXCEPTION_INIT },
   { "EXCLUSIVE", Y_EXCLUSIVE },
   { "EXEC_SQL", Y_EXEC_SQL },
   { "EXISTS", Y_EXISTS },
   { "EXIT", Y_EXIT },
   { "FALSE", Y_FALSE },
   { "FETCH", Y_FETCH },
   { "FIRST", Y_FIRST },
   { "FLOAT", Y_FLOAT },
   { "FOR", Y_FOR },
   { "FOREIGN", Y_FOREIGN },
   { "FROM", Y_FROM },
   { "FUNCTION", Y_FUNCTION },
   { "GLB", Y_GLB },
   { "GOTO", Y_GOTO },
   { "GRANT", Y_GRANT },
   { "GROUP", Y_GROUP },
   { "HAVING", Y_HAVING },
   { "IF", Y_IF },
   { "IN", Y_IN },
   { "INCREMENT", Y_INCREMENT },
   { "INDEX", Y_INDEX },
   { "INDICATOR", Y_INDICATOR },
   { "INSERT", Y_INSERT },
   { "INSERTING", Y_INSERTING },
   { "INTEGER", Y_INTEGER },
   { "INTERSECT", Y_INTERSECT },
   { "INTO", Y_INTO },
   { "IS", Y_IS },
   { "ISOLATION", Y_ISOLATION },
   { "KEY", Y_KEY },
   { "LAST", Y_LAST },
   { "LEVEL", Y_LEVEL },
   { "LIKE", Y_LIKE },
   { "LOCK", Y_LOCK },
   { "LONG", Y_LONG },
   { "LOOP", Y_LOOP },
   { "LUB", Y_LUB },
   { "MAX", Y_MAX },
   { "MAXVALUE", Y_MAXVALUE },
   { "MIN", Y_MIN },
   { "MINUS", Y_MINUS },
   { "MINVALUE", Y_MINVALUE },
   { "MLSLABEL", Y_MLSLABEL },
   { "MODE", Y_MODE },
   { "NATURAL", Y_NATURAL },
   { "NEW", Y_NEW },
   { "NEXT", Y_NEXT },
   { "NEXTVAL", Y_NEXTVAL },
   { "NOCACHE", Y_NOCACHE },
   { "NOCYCLE", Y_NOCYCLE },
   { "NOMAXVALUE", Y_NOMAXVALUE },
   { "NOMINVALUE", Y_NOMINVALUE },
   { "NOORDER", Y_NOORDER },
   { "NOT", Y_NOT },
   { "NOWAIT", Y_NOWAIT },
   { "NULL", Y_NULL },
   { "NUMBER", Y_NUMBER },
   { "NUMERIC", Y_NUMERIC },
   { "OF", Y_OF },
   { "OLD", Y_OLD },
   { "ON", Y_ON },
   { "ONLY", Y_ONLY },
   { "OPEN", Y_OPEN },
   { "OPTION", Y_OPTION },
   { "OR", Y_OR },
   { "ORDER", Y_ORDER },
   { "OTHERS", Y_OTHERS },
   { "OUT", Y_OUT },
   { "PACKAGE", Y_PACKAGE },
   { "POSITIVE", Y_POSITIVE },
   { "PRAGMA", Y_PRAGMA },
   { "PRECISION", Y_PRECISION },
   { "PRIMARY", Y_PRIMARY },
   { "PRIOR", Y_PRIOR },
   { "PRIVILEGES", Y_PRIVILEGES },
   { "PROCEDURE", Y_PROCEDURE },
   { "PUBLIC", Y_PUBLIC },
   { "RAISE", Y_RAISE },
   { "RANGE", Y_RANGE },
   { "RAW", Y_RAW },
   { "READ", Y_READ },
   { "REAL", Y_REAL },
   { "RECORD", Y_RECORD },
   { "REF", Y_REF },
   { "REFERENCES", Y_REFERENCES },
   { "REFERENCING", Y_REFERENCING },
   { "REPLACE", Y_REPLACE },
   { "RESTRICT_REFERENCES", Y_RESTRICT_REFERENCES },
   { "RETURN", Y_RETURN },
   { "REVERSE", Y_REVERSE },
   { "RNDS", Y_RNDS },
   { "RNPS", Y_RNPS },
   { "ROLLBACK", Y_ROLLBACK },
   { "ROW", Y_ROW },
   { "ROWID", Y_ROWID },
   { "SAVEPOINT", Y_SAVEPOINT },
   { "SCHEMA", Y_SCHEMA },
   { "SEGMENT", Y_SEGMENT },
   { "SELECT", Y_SELECT },
   { "SEQUENCE", Y_SEQUENCE },
   { "SERIALIZABLE", Y_SERIALIZABLE },
   { "SET", Y_SET },
   { "SHARE", Y_SHARE },
   { "SMALLINT", Y_SMALLINT },
   { "SOME", Y_SOME },
   { "SQL", Y_SQL },
   { "SQLCODE", Y_SQLCODE },
   { "SQLERRM", Y_SQLERRM },
   { "START", Y_START },
   { "STDDEV", Y_STDDEV },
   { "STRING", Y_STRING },
   { "SUBTYPE", Y_SUBTYPE },
   { "SUM", Y_SUM },
   { "SYNONYM", Y_SYNONYM },
   { "TABLE", Y_TABLE },
   { "THEN", Y_THEN },
   { "TO", Y_TO },
   { "TRANSACTION", Y_TRANSACTION },
   { "TRIGGER", Y_TRIGGER },
   { "TRUE", Y_TRUE },
   { "TYPE", Y_TYPE },
   { "UNION", Y_UNION },
   { "UNIQUE", Y_UNIQUE },
   { "UPDATE", Y_UPDATE },
   { "UPDATING", Y_UPDATING },
   { "USE", Y_USE },
   { "USER", Y_USER },
   { "VALUES", Y_VALUES },
   { "VARCHAR", Y_VARCHAR },
   { "VARCHAR2", Y_VARCHAR2 },
   { "VARIANCE", Y_VARIANCE },
   { "VIEW", Y_VIEW },
   { "WHEN", Y_WHEN },
   { "WHERE", Y_WHERE },
   { "WHILE", Y_WHILE },
   { "WITH", Y_WITH },
   { "WNDS", Y_WNDS },
   { "WNPS", Y_WNPS },
   { "WORK", Y_WORK },
   { "WRITE", Y_WRITE },
