// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "msdevintegrator.h"

/////////////////////////////////////////////////////////////////////////////
// CMSDEVIntegrator

IMPLEMENT_DYNCREATE(CMSDEVIntegrator, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CMSDEVIntegrator properties

/////////////////////////////////////////////////////////////////////////////
// CMSDEVIntegrator operations

void CMSDEVIntegrator::OpenFile(LPCTSTR filename, long line)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 filename, line);
}

void CMSDEVIntegrator::MakeSelection(LPCTSTR filename, long line, long column, LPCTSTR token)
{
	static BYTE parms[] =
		VTS_BSTR VTS_I4 VTS_I4 VTS_BSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 filename, line, column, token);
}

short CMSDEVIntegrator::GetTabSize()
{
	short result;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_I2, (void*)&result, NULL);
	return result;
}

void CMSDEVIntegrator::SetInfo(LPCTSTR info)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 info);
}

void CMSDEVIntegrator::GetSelection(BSTR* filename, BSTR* token, long* line, long* column)
{
	static BYTE parms[] =
		VTS_PBSTR VTS_PBSTR VTS_PI4 VTS_PI4;
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 filename, token, line, column);
}

void CMSDEVIntegrator::Exit()
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CMSDEVIntegrator::Command(LPCTSTR string)
{
	static BYTE parms[] =
		VTS_BSTR;
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 string);
}

void CMSDEVIntegrator::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
