#!/bin/sh

checkedout="0"
lockfile="`dirname $cm_revision_file`/p.`basename $cm_workfile`"
if [ -f $lockfile ]; then
    grep $USER $lockfile > /dev/null
    if [ $? -eq 0 ]; then
	checkedout="1"
    fi    
fi

if [ "$checkedout" = "0" ]; then
    sccs edit -s -p $cm_revision_file > /dev/null
    if [ $? -ne 0 ]; then
        echo "%% lock failed"
	exit 1
    fi
fi
