#!/bin/sh

checkedout="0"
lockfile="`dirname $cm_revision_file`/p.`basename $cm_workfile`"
if [ -f $lockfile ]; then
    grep $USER $lockfile > /dev/null
    if [ $? -eq 0 ]; then
	checkedout="1"
    fi    
fi

if [ "$checkedout" = "1" ]; then
    $PSETCFG/util/sccs_lockfile_version < $lockfile
else
    sccs prs -e -d":I:" $cm_revision_file
fi
