default:
	$(MAKE) -C ../../../../ -f new-rules/make-one-prog.mk \
	PROG=discover/model_server/xref/test/prog.mk

clean:
	$(MAKE) -C ../../../../ -f new-rules/make-one-prog.mk \
	PROG=discover/model_server/xref/test/prog.mk \
	clean

include ../../../../new-rules/new-testsuite.mk
