#!/bin/sh
#mg

minus='-'
if [ "$1" = "$minus" ] ; 
then 
  shift
  ps=$1
  shift
  flag=1; 
else
 tmp_dir=${PTEST_TMPDIR:-/usr/tmp}
 ps=$tmp_dir/ps.$$
 case "$Arch" in
    sun4) /bin/ps -l | grep -v $0 | grep -v grep |\
           sed -n 's/[ ]*[^ ]*[ ]*[^ ]*\(......\)\(......\).*/\2 \1/p' > $ps ;;
    *)  /bin/ps -l | grep -v $0 | grep -v grep |\
           sed -n 's/[ ]*[^ ]*[ ]*[^ ]*[ ]*[^ ]*\(......\)\(......\).*/\2 \1/p' > $ps ;;
 esac

 flag=0; 
fi

for ii in $*
do
 $0 $minus $ps `awk '{if($1==pid) print $2 }' pid=$ii $ps`
 if [ $flag -eq 1 ] ; then echo $ii ; fi
done

if [ $flag -eq 0 ] ; then rm $ps ; fi
