#!/bin/csh -f


if ( "$1" == "" ) then
    echo "Usage: test_copy test_name [dest_test_name]"
    exit 0
endif

set source = "$1"

if ( "$2"  == "" ) then
    set target = "$PSETTEST"
else
    set target = "$2"
endif

if ("$source" == "$target") then
    echo "ptest_copy: Source is equal to Target. Try different pathnames, please."
    exit 1
endif

if (-f $target) then
    echo "ptest_copy: Target is a file. Try directory name instead, please."
    exit 1
endif

if ( -d $source ) then 
    set source = "$1"
else if ( -f $source) then 
    set source = `/bin/dirname $1`
else     
    echo "ptest_copy: Test $source does not exist"
    set "$2" = ""
    exit 1
endif

if (-d $target) then
    set w_cnt = `echo $target/.* $target/* | wc -w`
    if (! $?PTEST_ALL && "$w_cnt" != "2") then
       ls -A $target/
       echo -n "ptest_copy: Target $target is going to be overwritten [y|n]? "
       set answer = "$<"
       if ( $answer != "y" ) then
          echo "ptest_copy: Rejected."
	  exit 1
       else
	  echo -n "Wiping up $target ... "
	  \rm -rf $target >&! /dev/null
          mkdir $target
          echo "Done"
       endif
    endif
else
    echo -n "ptest_copy: Create a target directory [y|n]? "
    set answer = "$<"
    if ( $answer == "y" ) then
        mkdir -p "$target"
    endif
endif

if (! -d $target) then
    echo "ptest_copy: Target directory does not exist."
    exit 1
endif

         echo -n "Copy $source TO $target ... "
	 set here=`pwd`
	 cd $source
         tar cf - . | (cd $target; tar xf -)
	 (cd $target; chmod -R a+w . )
         echo "Done"
	 cd $here
echo ""




