#!/bin/sh
[ -z "$1" -o -z "$2" ] && 
{
	echo "Usage: $0 dir [args] filename"
	exit 1;
}

[ -z "$1" ] && exit;
[ ! -d "$1" ] &&
{
	echo "Argument not directory [$1]."
	exit 1;
}

scriptname=`basename $0`
testdir="$1"
shift
$testdir/$scriptname $*
