#!/bin/sh
# cm_diff (ClearCase) - Do a diff of a source file

# exit script if we get any errors
set -e

# Get branch
branch=`cleartool describe -pre -short $cm_revision_file | sed -e 's%/main/\(.*\)/[^/]*%\1%' -e 's%/main/[^/]*%main%'`

# Get the current version for this file
currentversion=`cleartool lshistory -branch $branch $cm_workfile 2> /dev/null \
 		| $PSETCFG/util/atria_revisions_only | head -1`

# Display the diff in the configshell output window
cleartool diff -diff_format $cm_options $cm_workfile@@$currentversion $cm_workfile 2>&1

exit 0


#### Parameters    : None
#### Return values : 0 = success, !0 = failure
#### Output	   : stdout = Output of diff command (displayed in configshell)
		   : stderr = error messages (displayed in config status dialog box)

#### Environment Variables
# Environment variables setup by DISCOVER for ALL config scripts:
#	$PSETCFG	  - path to directory containing the config scripts
# Additional environment variables setup for this script by the configurator:
#	$cm_workfile	  - path to local (private) copy of file to be processed
#	$cm_options       - user defined options as configured in Configurator
#			    preferences dialog box
