#!/bin/sh
# cm_delete_pset (ClearCase) - Delete (uncheckout for ClearCase) .pset file

# exit script if we get any errors
set -e

set +e
version=`cleartool describe $cm_workfile 2> /dev/null | head -1 | grep 'version'`
set -e

if [ "$version" = "" ] ; then
  \rm -f $cm_workfile 2> /dev/null
else
  # Uncheckout it so that we see the system version again
  cleartool uncheckout -rm $cm_options $cm_workfile
fi

exit 0


#### Parameters    : None
#### Return values : 0 = success, !0 = failure
#### Output	   : stdout = informational (displayed in configshell)
		   : stderr = error messages (displayed in config status dialog box)

#### Environment Variables
# Environment variables setup for this script by the configurator:
#	$cm_workfile	  - path to local (private) copy of file to be processed
#	$cm_options       - user defined options as configured in Configurator
#			    preferences dialog box for delete
