#!/bin/sh
# cm_obsolete_src (ClearCase) - Obsolete source file.

# exit script if we get any errors
set -e

if [ -f $cm_workfile ] ; then
  #Checkout current directory if it was not checked out
  #directory=`echo $cm_workfile | sed -e 's?\(.*\)/\([^/]*\)?\1?'`
  directory=`dirname $cm_workfile`

  # Check out directory (ignore errors if it is already checked out)
  set +e
  echo "cleartool checkout -reserve -nc $directory"
  cleartool checkout -reserve -nc $directory
  set -e

  #Remove name
  echo "cleartool rmname -nc $cm_workfile"
  cleartool rmname -nc $cm_workfile

  # Check the directory back in
  echo "cleartool checkin -nc $directory"
  cleartool checkin -nc $directory

fi

exit 0
