#!/bin/sh
# cm_setup_pset (ClearCase) - Call pending filter

# exit script if we get any errors
set -e

# Get our command line options
workingdir=$1
workingfile=$2
systemdir=$3
systemfile=$4

# Find the version of the file selected by the view
set +e
viewversion=`cleartool describe $systemdir/$systemfile 2> /dev/null | head -1 | \
             $PSETCFG/util/atria_revisions`
set -e

# Report the version extended filenameback to the configurator via stdout
if [ "$viewversion" = "" ]; then
  echo "$systemdir/$systemfile" >&1

  if [ "$systemdir/$systemfile" != "$workingdir/$workingfile" ] ; then
    exit 0
  else
    # exit status 99 means that the file is not an element in ClearCase
    # cm_create will be called before cm_put_src is called
    exit 99
  fi

else
  # Extract the branch from the viewversion
  branch=`dirname $viewversion`

  # Find the version of the latest version on the branch
  latestversion=`cleartool describe $systemdir/$systemfile@@$branch/LATEST \
	| head -1 | $PSETCFG/util/atria_revisions`

  echo "$systemdir/$systemfile@@$latestversion" >&1
fi

exit 0


#### Parameters    : $1 = working (private) directory
		   : $2 = working (private) filename
		   : $3 = system (public) directory
		   : $4 = system (public) filename
		   : $5 = "copy_pset" if configurator going to call cm_copy_pset next
#### Return values : 0 = success, !0 = failure
#### Output	   : stdout = first line of output is used by configurator to
		              set the value of cm_sysfile for the next script it calls
		   : stderr = ignored

#### Environment Variables
# Environment variables setup by DISCOVER for ALL config scripts:
#	$PSETCFG	  - path to directory containing the config scripts
#	$cm_optscripts    - Points to the directory of optional scripts

#### Optional Scripts
#	cm_pendfilt	  - Filter to transform source and pset filenames before ci/co
