#!/bin/sh
# cm_unlock (ClearCase) - Change a checkout to unreserved

# exit script if we get any errors
set -e

# Check if file is already unlocked
set +e
lockstring=`cleartool lscheckout $cm_workfile | grep '(reserved)$' 2>/dev/null`
set -e

# Unlock if locked
if [ "$lockstring" != "" ]; then
   echo "cleartool unreserve -cq $cm_options $cm_workfile <${cm_description:=/dev/null}"
         cleartool unreserve -cq $cm_options $cm_workfile <${cm_description:=/dev/null}
fi

exit 0

#### Parameters    : None
#### Return values : 0 = success, !0 = failure
#### Output	   : stdout = informational (displayed in configshell)
		   : stderr = error messages (displayed in config status dialog box)

#### Environment Variables
# Environment variables setup for this script by the configurator:
#	$cm_workfile	  - path to local (private) copy of file to be processed
#	$cm_options       - user defined options as configured in Configurator
#			    preferences dialog box for unlock
#	$cm_description   - path pointing to file containing users comments
