#!/bin/sh
# cm_unget_pset (ClearCase) - Uncheckout the .pset file.

# exit script if we get any errors
set -e

if [ "$cm_sysfile" = "" ] ; then
  echo "The variable cm_sysfile is not set"
  exit 0
fi 

if [ "$cm_workfile" = "" ] ; then
  echo "The variable cm_workfile is not set"
  exit 0
fi


# Find the version of the file selected by the view
set +e
viewversion=`cleartool describe $cm_workfile 2> /dev/null | head -1 | \
             $PSETCFG/util/atria_revisions`
set -e

if [ "$viewversion" = "" ] ; then
  # This is not a clearcase element
  echo "rm -f $cm_workfile"
  rm -f $cm_workfile
else



  set +e
  unreserved=`cleartool describe $cm_sysfile 2> /dev/null | grep CHECKEDOUT | grep reserved`
  set -e

  if [ "$unreserved" != "" ] ; then
    # if here it means that we have this file checkedout & reserved/unreserved
    # UnCheck out the file.
    echo "cleartool uncheckout -rm $cm_sysfile"
          cleartool uncheckout -rm $cm_sysfile
  fi
fi

exit 0
