#!/bin/sh
# cm_version (ClearCase) - Report the version of an element

# exit script if we get any errors
set -e

if [ "$cm_sys_proj" != "" ] ; then
  # Here cm_local_proj is just used as indicator.
  if [ "$cm_local_proj" = "" ] ; then
    # Return latest version on the branch specified by cm_sys_proj

    branch=`echo $cm_sys_proj | sed -e '/@@/!d' -e 's/^.*@@\(.*\)/\1/'`
    if [ "$branch" = "" ] ; then
      branch="main"
    fi
    cleartool lshist -nco -branch $branch $cm_revision_file | head -1 \
    | $PSETCFG/util/atria_revisions
  else
    branch=`echo $cm_sys_proj | sed -e '/@@/!d' -e 's/^.*@@\(.*\)/\1/'`
    if [ "$branch" = "" ] ; then
      branch="main"
    fi
    branch_start=`echo $cm_revision_file | sed -e "s%\(@@.*/$branch/.*/\).*%\10%"`
    cleartool describe -short -pred $branch_start
  fi
else
  # Report version via stdout
  cleartool describe $cm_revision_file | head -1 \
	  | $PSETCFG/util/atria_revisions
fi

exit 0


#### Parameters    : None
#### Return values : 0 = success, !0 = failure
#### Output	   : stdout = version of file
		   : stderr = ignored(?)

#### Environment Variables
# Environment variables setup by DISCOVER for ALL config scripts:
#	$PSETCFG	  - path to directory containing the config scripts
# Additional environment variables setup for this script by the configurator:
#	$cm_revison_file  - path to latest checked-in version
