#ifndef __QUERYRESULTS1_H__
#define __QUERYRESULTS1_H__

// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CQueryResults wrapper class

class CQueryResults : public CWnd
{
protected:
	DECLARE_DYNCREATE(CQueryResults)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x26c03863, 0xd33, 0x11d2, { 0xae, 0xe9, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetFullListName();
	void SetFullListName(LPCTSTR);
	CString GetFilterListName();
	void SetFilterListName(LPCTSTR);
	LPDISPATCH GetDataSource();
	void SetDataSource(LPDISPATCH);
	CString GetQuery();
	void SetQuery(LPCTSTR);
	CString GetFilter();
	void SetFilter(LPCTSTR);
	CString GetSort();
	void SetSort(LPCTSTR);
	long GetElement();
	void SetElement(long);
	CString GetSelectionName();
	void SetSelectionName(LPCTSTR);

// Operations
public:
	void Push();
	BOOL Pop();
	void Update();
	long AmountSelected();
	void Clear();
	long RowAmount();
	long FilteredAmount();
	void ApplyAttributeChanges();
	void CancelAttributeChanges();
	void AddAttribute(LPCTSTR logname, LPCTSTR option);
	void RemoveAttribute(LPCTSTR logname, LPCTSTR option);
	BOOL CheckAttribute(LPCTSTR logname, LPCTSTR option);
	void AboutBox();
};

#endif // __QUERYRESULTS1_H__
