// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datasource.h"

/////////////////////////////////////////////////////////////////////////////
// CDataSource

IMPLEMENT_DYNCREATE(CDataSource, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CDataSource properties

/////////////////////////////////////////////////////////////////////////////
// CDataSource operations

CString CDataSource::AccessSync(BSTR* command)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x1, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		command);
	return result;
}

CString CDataSource::AccessOutput(BSTR* query)
{
	CString result;
	static BYTE parms[] =
		VTS_PBSTR;
	InvokeHelper(0x2, DISPATCH_METHOD, VT_BSTR, (void*)&result, parms,
		query);
	return result;
}

BOOL CDataSource::IsConnectionLost()
{
	BOOL result;
	InvokeHelper(0x9, DISPATCH_METHOD, VT_BOOL, (void*)&result, NULL);
	return result;
}

void CDataSource::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
