// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "groupscombo.h"

/////////////////////////////////////////////////////////////////////////////
// CGroupsCombo

IMPLEMENT_DYNCREATE(CGroupsCombo, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CGroupsCombo properties

CString CGroupsCombo::GetSelectionVariable()
{
	CString result;
	GetProperty(0x1, VT_BSTR, (void*)&result);
	return result;
}

void CGroupsCombo::SetSelectionVariable(LPCTSTR propVal)
{
	SetProperty(0x1, VT_BSTR, propVal);
}

LPDISPATCH CGroupsCombo::GetDataSource()
{
	LPDISPATCH result;
	GetProperty(0x2, VT_DISPATCH, (void*)&result);
	return result;
}

void CGroupsCombo::SetDataSource(LPDISPATCH propVal)
{
	SetProperty(0x2, VT_DISPATCH, propVal);
}

CString CGroupsCombo::GetOutputVariable()
{
	CString result;
	GetProperty(0x3, VT_BSTR, (void*)&result);
	return result;
}

void CGroupsCombo::SetOutputVariable(LPCTSTR propVal)
{
	SetProperty(0x3, VT_BSTR, propVal);
}

CString CGroupsCombo::GetCaption()
{
	CString result;
	GetProperty(DISPID_CAPTION, VT_BSTR, (void*)&result);
	return result;
}

void CGroupsCombo::SetCaption(LPCTSTR propVal)
{
	SetProperty(DISPID_CAPTION, VT_BSTR, propVal);
}

BOOL CGroupsCombo::GetControlsEnable()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CGroupsCombo::SetControlsEnable(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGroupsCombo operations

void CGroupsCombo::Update()
{
	InvokeHelper(0x5, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

CString CGroupsCombo::GetSelectedGroups()
{
	CString result;
	InvokeHelper(0x6, DISPATCH_METHOD, VT_BSTR, (void*)&result, NULL);
	return result;
}

void CGroupsCombo::CreateGroup()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGroupsCombo::AddElements()
{
	InvokeHelper(0x8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CGroupsCombo::AboutBox()
{
	InvokeHelper(0xfffffdd8, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
