#!/bin/sh

if [ "$cm_optscripts" != "" -a -f $cm_optscripts/cm_beforeput ] ; then
  $cm_optscripts/cm_beforeput
  if [ $? -ne 0 ] ; then 
      echo "%% put fail" >&2
      exit 1
  fi
fi

echo "ccm ci $cm_options $cm_workfile < ${cm_description:=/dev/null}"
ccm ci $cm_options $cm_workfile < ${cm_description:=/dev/null}

if [ $? -eq 0 ] ; then 

  if [ "$cm_optscripts" != "" -a -f $cm_optscripts/cm_afterput ] ; then
    $cm_optscripts/cm_afterput &
  fi

  exit 0

fi

exit 1
