#if !defined(AFX_CATEGORIESCOMBO_H__643A5C81_DA9E_11D2_AF95_00A0C9B71DC4__INCLUDED_)
#define AFX_CATEGORIESCOMBO_H__643A5C81_DA9E_11D2_AF95_00A0C9B71DC4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCategoriesCombo wrapper class

class CCategoriesCombo : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCategoriesCombo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2451d66c, 0x1203, 0x11d2, { 0xae, 0xed, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	LPDISPATCH GetDataSource();
	void SetDataSource(LPDISPATCH);
	CString GetCaption();
	void SetCaption(LPCTSTR);

// Operations
public:
	CString AccessFromName(LPCTSTR name);
	CString GetCategoriesList();
	void Update();
	void Unselect();
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CATEGORIESCOMBO_H__643A5C81_DA9E_11D2_AF95_00A0C9B71DC4__INCLUDED_)
