// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CCBrowserFrame wrapper class

class CCBrowserFrame : public CWnd
{
protected:
	DECLARE_DYNCREATE(CCBrowserFrame)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x1de4f494, 0x201b, 0x11d2, { 0xae, 0xf3, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	CString GetArguments();
	void SetArguments(LPCTSTR);
	CString GetResultsFromCategory();
	void SetResultsFromCategory(LPCTSTR);
	CString GetResultsFromQuery();
	void SetResultsFromQuery(LPCTSTR);
	CString GetResultsFromGroup();
	void SetResultsFromGroup(LPCTSTR);
	CString GetSelectionFromQuery();
	void SetSelectionFromQuery(LPCTSTR);
	CString GetSelectionFromCategory();
	void SetSelectionFromCategory(LPCTSTR);
	CString GetSelectionFromGroup();
	void SetSelectionFromGroup(LPCTSTR);
	CString GetProjects();
	void SetProjects(LPCTSTR);
	short GetMode();
	void SetMode(short);
	LPDISPATCH GetDataSource();
	void SetDataSource(LPDISPATCH);
	CString GetSelectedCategories();
	void SetSelectedCategories(LPCTSTR);

// Operations
public:
	void Update();
	void SetSet(LPCTSTR name);
	void AboutBox();
};
