#if !defined(AFX_IMPACT_H__9A481F14_03B4_4F3C_90CF_B1227EF2ADC1__INCLUDED_)
#define AFX_IMPACT_H__9A481F14_03B4_4F3C_90CF_B1227EF2ADC1__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CImpactCtrl wrapper class

class CImpactCtrl : public CWnd
{
protected:
	DECLARE_DYNCREATE(CImpactCtrl)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x2047b32d, 0x6d1b, 0x4538, { 0x9a, 0xf5, 0x41, 0xf7, 0xb8, 0xd0, 0xbd, 0xbe } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	LPDISPATCH GetDataSource();
	void SetDataSource(LPDISPATCH);
	LPDISPATCH GetEditorCtrl();
	void SetEditorCtrl(LPDISPATCH);

// Operations
public:
	BOOL Update();
	BOOL SaveReportTo(LPCTSTR szFileName);
	BOOL IsReportView();
	CString GetReportName();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_IMPACT_H__9A481F14_03B4_4F3C_90CF_B1227EF2ADC1__INCLUDED_)
