// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CMSDEVIntegrator wrapper class

class CMSDEVIntegrator : public CWnd
{
protected:
	DECLARE_DYNCREATE(CMSDEVIntegrator)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xaa00dc08, 0x36de, 0x11d2, { 0xaf, 0xf, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void OpenFile(LPCTSTR filename, long line);
	void MakeSelection(LPCTSTR filename, long line, long column, LPCTSTR token);
	short GetTabSize();
	void SetInfo(LPCTSTR info);
	void GetSelection(BSTR* filename, BSTR* token, long* line, long* column);
	void Exit();
	void Command(LPCTSTR string);
	void AboutBox();
};
