// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CQueriesCombo wrapper class

class CQueriesCombo : public CWnd
{
protected:
	DECLARE_DYNCREATE(CQueriesCombo)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0x6e672c25, 0x1543, 0x11d2, { 0xae, 0xed, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	LPDISPATCH GetDataSource();
	void SetDataSource(LPDISPATCH);
	CString GetSelection();
	void SetSelection(LPCTSTR);
	CString GetCategories();
	void SetCategories(LPCTSTR);
	CString GetCaption();
	void SetCaption(LPCTSTR);

// Operations
public:
	CString AccessFromName(LPCTSTR name);
	void Update();
	CString GetQueriesList();
	void Clear();
	CString GetSelectedQueries();
	void AboutBox();
};
