// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CReportTemplate wrapper class

class CReportTemplate : public CWnd
{
protected:
	DECLARE_DYNCREATE(CReportTemplate)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xb0a92ba6, 0x41ac, 0x11d2, { 0xaf, 0x18, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:

// Operations
public:
	void AddChild(short type, LPCTSTR tag, LPCTSTR text);
	void AddSibling(short type, LPCTSTR tag, LPCTSTR text);
	void Save(LPCTSTR fname);
	BOOL Load(LPCTSTR fname);
	void DeleteCurrent();
	CString MakeXML();
	BOOL ChangeCurrent(short type, LPCTSTR tag, LPCTSTR text);
	short GetType();
	CString GetTag();
	CString GetText();
	CString GetTagsList();
	void Clear();
	void AddParent(short type, LPCTSTR tag, LPCTSTR text);
	long FindToken(LPCTSTR token);
	void AboutBox();
};
