//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DiscoverMDI.rc
//
#define ID_BTN3                         3
#define ID_APPLY                        3
#define IDR_DISCOVTYPE_SRVR_IP          4
#define IDR_DISCOVTYPE_SRVR_EMB         5
#define IDR_DISCOVTYPE_CNTR_IP          6
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_FAILED_TO_CREATE            102
#define IDR_DISCOVERMDI                 103
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_DATACHART                   109
#define IDR_MAINFRAME                   128
#define IDR_DISCOVTYPE                  129
#define IDD_PROJECTBROWSER              130
#define IDD_LEFTMODELBROWSER            132
#define IDD_RIGHTMODELBROWSER           134
#define IDB_ARLEFT                      139
#define IDB_ARRIGHT                     140
#define IDD_ADDTPM                      144
#define IDD_NEWFILTER                   145
#define IDB_COLLECT                     148
#define IDB_FILTER                      149
#define IDB_PATTERN                     150
#define IDB_INSTANCES                   151
#define IDB_ASSIGNMENTS                 152
#define IDB_REPORT                      153
#define IDB_QUERY                       154
#define IDI_ICON1                       155
#define IDB_DIFF                        156
#define IDB_NEWTASK                     158
#define IDD_NEWTASKFLOW                 159
#define IDR_TPM                         160
#define IDR_XML                         164
#define IDD_XMLADDNODE                  166
#define IDD_XMLSETUP                    169
#define IDD_XMLARGUMENTS                171
#define IDB_XMLARGDLG                   172
#define IDR_DORMANT                     178
#define IDR_QA                          180
#define IDB_OUTDATED                    181
#define IDR_ACCESS                      181
#define IDB_CHANGETOCOMPILE             182
#define IDR_MAINFRAMEVIEWS              184
#define IDR_DATACHARTVIEW               184
#define IDR_QA1                         185
#define IDR_ERDVIEW                     185
#define IDR_FLOWCHARTVIEW               186
#define IDR_INHERITANCEVIEW             187
#define IDR_OUTLINEVIEW                 188
#define IDR_TREEVIEW                    189
#define IDR_SIMPLIFY                    191
#define IDD_QATREE                      193
#define IDD_QAPARAMS                    194
#define IDB_FOLDER_CLOSED               197
#define IDD_SERVICECHOOSER              199
#define IDD_GROUPSVIEW                  201
#define IDD_XMLCOMPNAME                 203
#define IDD_PROMPT                      204
#define IDB_ARROWRIGHT                  206
#define IDD_TPMMATCH                    206
#define IDB_ARROWLEFT                   207
#define IDC_NEW                         207
#define IDC_TPMPROP                     210
#define IDB_AND                         211
#define IDC_TPMSEL                      211
#define IDB_OR                          212
#define IDB_FILTERLIST                  213
#define IDB_PUBLIC                      214
#define IDB_RTOL                        215
#define IDB_FILTERWIZARD                216
#define IDD_DIALOG1                     216
#define IDD_HIDE_NODES                  216
#define IDB_ARROWUP                     218
#define IDB_ARROWDN                     219
#define IDB_FILESNEEDED                 221
#define IDB_COMPLETESEARCH              222
#define IDB_FILESNEEDEDCOMPILE          223
#define IDB_FILESNEEDEDGET              224
#define IDB_QUERY1_OPEN                 225
#define IDB_QUERY2_OPEN                 226
#define IDB_QUERY_OPEN_DIS              227
#define IDB_FOLDER_OPENED_DIS           232
#define IDB_FOLDER_OPENED               233
#define IDB_FOLDER_CLOSED_DIS           234
#define IDB_QUERY1_CLOSE                235
#define IDB_QUERY2_CLOSE                236
#define IDB_QUERY_CLOSE_DIS             237
#define IDB_PASTE                       238
#define IDB_COPY                        239
#define IDB_STOP                        240
#define IDB_XMLCOMPONENT                241
#define IDB_FONTS                       242
#define IDB_SUBOK_SEL                   243
#define IDB_SUBMIT_OK_OPENED            244
#define IDB_SUBOK_UNSEL                 244
#define IDB_SUBMIT_OK_CLOSED_DIS        245
#define IDB_SUBOK_SEL_DIS               245
#define IDB_SUBMIT_OK_OPENED_DIS        246
#define IDB_SUBOK_UNSEL_DIS             246
#define IDB_QUERY_OPEN_DIS1             247
#define IDB_SUBWARN_SEL                 247
#define IDB_SUBWARN_SEL_DIS             248
#define IDB_SUBWARN_UNSEL               249
#define IDB_SUBWARN_UNSEL_DIS           250
#define IDB_SUBERROR_SEL                251
#define IDB_SUBERROR_SEL_DIS            252
#define IDB_SUBERROR_UNSEL              253
#define IDB_SUBERROR_UNSEL_DIS          254
#define IDB_FOLDER_ERROR_CLOSED         256
#define IDB_FOLDER_ERROR_OPENED         257
#define IDB_FOLDER_ERROR_CLOSED_DIS     258
#define IDB_FOLDER_ERROR_OPENED_DIS     259
#define IDB_FOLDER_WARN_CLOSED          260
#define IDB_FOLDER_WARN_CLOSED_DIS      261
#define IDB_FOLDER_WARN_OPENED          262
#define IDB_FOLDER_WARN_OPENED_DIS      263
#define IDB_PROTECTED                   266
#define IDB_PRIVATE                     267
#define IDB_CLASSBMP                    268
#define IDB_LTOR                        269
#define IDB_BTOT                        270
#define IDB_TTOB                        271
#define IDB_ONE2MANY_TOP                272
#define IDB_ONE2MANY_BOTTOM             273
#define IDB_ONE2MANY_LEFT               274
#define IDB_ONE2MANY_RIGHT              275
#define IDR_ERDTOOLS                    282
#define IDR_DATATOOLS                   283
#define IDR_TREETOOLS                   284
#define IDD_UPDATEWAIT                  284
#define IDR_INHERITANCETOOLS            285
#define IDR_OUTLINETOOLS                286
#define IDR_FLOWCHARTTOOLS              287
#define IDD_DIALOG2                     287
#define IDD_GRAPH_LAYOUT                288
#define IDB_GRAPH_EXPAND                290
#define IDB_GRAPH_COLLAPSE              291
#define IDB_NV_PUB_FUNC                 292
#define IDB_NV_PROT_FUNC                293
#define IDB_NV_PRIV_FUNC                294
#define IDD_CHECKIN                     294
#define IDB_NV_PACK_FUNC                295
#define IDB_NV_PUB_PROP                 296
#define IDB_NV_PROT_PROP                297
#define IDB_NV_PRIV_PROP                298
#define IDD_QUESTIONDLG                 298
#define IDB_NV_PACK_PROP                299
#define IDB_VV_PUB_FUNC                 300
#define IDB_VV_PROT_FUNC                301
#define IDB_VV_PRIV_FUNC                302
#define IDB_VV_PACK_FUNC                303
#define IDB_BROWSER_SPLIT               304
#define IDD_ATTRIBUTES                  305
#define IDB_BROWSER_PREV                305
#define IDB_BROWSER_NEXT                306
#define IDB_BROWSER_PROJECTS            307
#define IDB_BROWSER_CATEGORIES          308
#define IDD_CALLGRAPH                   308
#define IDB_BROWSER_QUERIES             309
#define IDD_FILTERLIST                  310
#define IDB_BROWSER_GROUPS              310
#define IDB_PROJECTS                    311
#define IDB_SIMPLIFY_ROOT               312
#define IDB_SIMPLIFY_CHECK              313
#define IDB_SIMPLIFY_UNCHECK            314
#define IDD_SORT                        315
#define IDB_SIMPLIFY_PERMANENT          315
#define IDB_SIMPLIFY_ROOT_SEL           316
#define IDB_SIMPLIFY_CHECK_SEL          317
#define IDB_SIMPLIFY_UNCHECK_SEL        318
#define IDB_SIMPLIFY_UNPROCESSED        319
#define IDD_FILTERWIZARD                320
#define IDB_SIMPLIFY_VISITED            320
#define IDD_COMMONVIEW                  321
#define IDB_SIMPLIFY_UPDATED            321
#define IDD_TPMFILTER                   322
#define IDB_SIMPLIFY_PROCESSING         322
#define IDD_TPMFLOW                     323
#define IDB_INSTANCE                    323
#define IDD_FLOWTASKS                   324
#define IDD_FORMVIEW                    325
#define IDD_XMLSTYLES                   326
#define IDD_DORMANT                     328
#define IDD_MINIBROWSER                 330
#define IDD_ACCESS                      331
#define IDD_SUBMITPROP                  333
#define IDD_SUBMITINFO                  334
#define IDD_DLGBAR                      335
#define IDD_GRAPH_NODE                  336
#define IDD_GRAPH_EDGE                  337
#define IDD_GRAPH_INHERITANCE           338
#define IDD_GRAPH_ERD                   339
#define IDD_CHECKOUT                    340
#define IDD_UNCHECKOUT                  341
#define IDD_LOCK                        342
#define IDD_UNLOCK                      343
#define IDD_FLOATINGBROWSER             344
#define IDD_DOCKABLEBROWSER             345
#define IDD_SIMPLIFY_TREE               347
#define IDD_SIMPLIFY_SELECTION          348
#define IDD_SIMPLIFY_TEXT               349
#define IDD_SEVSAVE                     353
#define IDD_SEVOPEN                     354
#define IDD_SEVERRORS                   358
#define IDD_ERRORSBROWSER               360
#define IDD_LISTSEL                     363
#define IDD_EDITORSELECTORDLG           366
#define IDB_ABOUT                       369
#define IDD_CMSELECTORDLG               370
#define IDD_ATTRIBUTESDLG               371
#define IDR_IMPACT                      373
#define IDD_IMPACT                      375
#define IDD_IMATTACHMENT                381
#define IDD_WAITDLG                     382
#define IDB_WAIT                        383
#define IDB_MODELIMAGES                 384
#define IDD_SERVICEMANAGER_DIALOG       385
#define IDS_NAME_COLUMN                 501
#define IDS_FILE_COLUMN                 502
#define IDS_EXTENTION_COLUMN            503
#define IDS_LINE_COLUMN                 504
#define IDS_TYPE_COLUMN                 505
#define IDS_ARGNUM_COLUMN               506
#define IDS_ARGS_COLUMN                 507
#define IDS_KIND_COLUMN                 508
#define IDS_LANGUAGE_COLUMN             509
#define IDS_MODELFILE_COLUMN            510
#define IDS_CYCLCOMPLEXITY_COLUMN       511
#define IDS_MYERCOMPLEXITY_COLUMN       512
#define IDS_SUPERCLASSES_COLUMN         513
#define IDS_SUBCLASSES_COLUMN           514
#define IDS_SIZE_COLUMN                 515
#define IDS_DEPTH_COLUMN                516
#define IDS_DANGLINGELSEIF_COLUMN       517
#define IDS_DEFLESSSWITCH_COLUMN        518
#define IDS_START_COLUMN                519
#define IDS_RETURN_COLUMN               520
#define IDS_LINESAMOUNT_COLUMN          521
#define IDS_UNCOMMENTAMOUNT_COLUMN      522
#define IDS_EXECUTABLEAMOUNT_COLUMN     523
#define IDS_IFSAMOUNT_COLUMN            524
#define IDS_LOOPSAMOUNT_COLUMN          525
#define IDS_SWITCHESAMOUNT_COLUMN       526
#define IDS_DEFAULTAMOUNT_COLUMN        527
#define IDS_STATUS_COLUMN               528
#define IDS_NAME_COMMAND                601
#define IDS_FILE_COMMAND                602
#define IDS_EXTENTION_COMMAND           603
#define IDS_LINE_COMMAND                604
#define IDS_TYPE_COMMAND                605
#define IDS_ARGNUM_COMMAND              606
#define IDS_ARGS_COMMAND                607
#define IDS_KIND_COMMAND                608
#define IDS_LANGUAGE_COMMAND            609
#define IDS_MODELFILE_COMMAND           610
#define IDS_CYCLCOMPLEXITY_COMMAND      611
#define IDS_MYERCOMPLEXITY_COMMAND      612
#define IDS_SUPERCLASSES_COMMAND        613
#define IDS_SUBCLASSES_COMMAND          614
#define IDS_SIZE_COMMAND                615
#define IDS_DEPTH_COMMAND               616
#define IDS_DANGLINGELSEIF_COMMAND      617
#define IDS_DEFLESSSWITCH_COMMAND       618
#define IDS_START_COMMAND               619
#define IDS_RETURN_COMMAND              620
#define IDS_LINESAMOUNT_COMMAND         621
#define IDS_UNCOMMENTAMOUNT_COMMAND     622
#define IDS_EXECUTABLEAMOUNT_COMMAND    623
#define IDS_IFSAMOUNT_COMMAND           624
#define IDS_LOOPSAMOUNT_COMMAND         625
#define IDS_SWITCHESAMOUNT_COMMAND      626
#define IDS_DEFAULTAMOUNT_COMMAND       627
#define IDS_STATUS_COMMAND              628
#define IDS_NAME_TYPE                   701
#define IDS_FILE_TYPE                   702
#define IDS_EXTENTION_TYPE              703
#define IDS_LINE_TYPE                   704
#define IDS_TYPE_TYPE                   705
#define IDS_ARGNUM_TYPE                 706
#define IDS_ARGS_TYPE                   707
#define IDS_KIND_TYPE                   708
#define IDS_LANGUAGE_TYPE               709
#define IDS_MODELFILE_TYPE              710
#define IDS_CYCLCOMPLEXITY_TYPE         711
#define IDS_MYERCOMPLEXITY_TYPE         712
#define IDS_SUPERCLASSES_TYPE           713
#define IDS_SUBCLASSES_TYPE             714
#define IDS_SIZE_TYPE                   715
#define IDS_DEPTH_TYPE                  716
#define IDS_DANGLINGELSEIF_TYPE         717
#define IDS_DEFLESSSWITCH_TYPE          718
#define IDS_START_TYPE                  719
#define IDS_RETURN_TYPE                 720
#define IDS_LINESAMOUNT_TYPE            721
#define IDS_UNCOMMENTAMOUNT_TYPE        722
#define IDS_EXECUTABLEAMOUNT_TYPE       723
#define IDS_IFSAMOUNT_TYPE              724
#define IDS_LOOPSAMOUNT_TYPE            725
#define IDS_SWITCHESAMOUNT_TYPE         726
#define IDS_DEFAULTAMOUNT_TYPE          727
#define IDS_STATUS_TYPE                 728
#define IDS_FIELDMESSAGE                729
#define IDS_FIELDCAPTION                730
#define IDS_OP_INT                      800
#define IDS_OP_INT2                     801
#define IDS_OP_INT3                     802
#define IDS_OP_INT4                     803
#define IDS_OP_INT5                     804
#define IDS_OP_INT6                     805
#define IDS_OP_STR                      806
#define IDS_OP_STR2                     807
#define IDS_OP_STR3                     808
#define IDS_OP_STR4                     809
#define IDS_OP_STR5                     810
#define IDS_FMT_INT                     811
#define IDS_FMT_INT2                    812
#define IDS_FMT_INT3                    813
#define IDS_FMT_INT4                    814
#define IDS_FMT_INT5                    815
#define IDS_FMT_INT6                    816
#define IDS_FMT_STR                     817
#define IDS_FMT_STR2                    818
#define IDS_FMT_STR3                    819
#define IDS_FMT_STR4                    820
#define IDS_FMT_STR5                    821
#define IDC_MODESELECTOR                1000
#define IDAPPLY                         1000
#define IDC_PROJECTTREE                 1001
#define IDC_PROJECTMODULES              1002
#define IDC_DATASOURCE                  1003
#define IDC_LEFTBROWSER                 1004
#define IDC_AVAILABLEMODELS             1004
#define IDC_ARGUMENT                    1005
#define IDC_RIGHTBROWSER                1008
#define IDC_MEMBERS                     1012
#define IDC_SOURCELIST                  1013
#define IDC_DESTLIST                    1014
#define IDC_CONTROLSFRAME               1015
#define IDC_SOURCEATTR                  1015
#define IDC_MOVETOSOURCE                1016
#define IDC_MOVETODEST                  1017
#define IDC_CONTROL                     1019
#define IDC_TREE                        1019
#define IDC_DESTATTR                    1020
#define IDC_ONE_TO_SOURCE               1025
#define IDC_BROWSERSELECTOR             1025
#define IDC_MODULES                     1026
#define IDC_LEFTPANE                    1027
#define IDC_RIGHTPANE                   1028
#define IDC_ONE_TO_DEST                 1030
#define IDC_TYPESPREADSHEET             1030
#define IDC_TEXTSPREADSHEET             1031
#define IDC_ADDROW                      1034
#define IDC_OPERATION                   1035
#define IDC_DELROW                      1035
#define IDC_FILTERSELECTOR              1036
#define IDC_NEWFILTER                   1037
#define IDC_EDITROW                     1038
#define IDC_TABEXPRESSION               1040
#define IDC_FILTERTYPE                  1041
#define IDC_TPMSPREADSHEET              1042
#define IDC_INCLUSIVE                   1043
#define IDC_CURRENTEDIT                 1044
#define IDC_OR                          1045
#define IDC_NEWEDIT                     1046
#define IDC_COMMENTEDIT                 1047
#define IDC_FROMSELECTION               1048
#define IDC_CHANGE                      1049
#define IDC_AND                         1050
#define IDC_FILTEREDIT                  1050
#define IDC_TASKSPREADSHEET             1051
#define IDC_TASKFLOW                    1052
#define IDC_EDITEXPRESSION              1055
#define IDC_SEQUENCESELECTOR            1056
#define IDC_ATTRIBUTE                   1060
#define IDC_NEWSEQUENCE                 1060
#define IDC_SEQUENCECAPTION             1061
#define IDC_TASKSLIST                   1064
#define IDC_ADDBUTTON                   1065
#define IDC_CAPTION                     1066
#define IDC_MSDEVINTEGRATORCTRL1        1068
#define IDC_MSDEVINTEGRATOR             1069
#define IDC_REMOVEBUTTON                1070
#define IDC_DOCSTRUCTURE                1070
#define IDC_TAGTEXT                     1071
#define IDC_ADDCHILD                    1072
#define IDC_ADDSIBLING                  1073
#define IDC_ITEMTEXT                    1074
#define IDC_CHANGEBUTTON                1075
#define IDC_DELETENODE                  1075
#define IDC_ADDPARENT                   1076
#define IDC_TITLE                       1079
#define IDC_SAVELIST                    1080
#define IDC_TYPECOMBO                   1080
#define IDC_TAGTITLE                    1082
#define IDC_ITEMTITLE                   1083
#define IDC_TAGS                        1084
#define IDC_NAMEEDIT                    1085
#define IDC_TEXT                        1088
#define IDC_TEXTNAME                    1089
#define IDC_COMMANDEDIT                 1090
#define IDC_PROPERTIES                  1091
#define IDC_HTML                        1092
#define IDC_RULESEDITOR                 1093
#define IDC_SOURCE                      1095
#define IDC_TEMPLATESEDITOR             1096
#define IDC_XMLEDITOR                   1098
#define IDC_DESTINATION                 1100
#define IDC_HTMLEDITOR                  1100
#define IDC_HTMLCHECK                   1102
#define IDC_BROWSEREDITOR               1103
#define IDC_ADD                         1105
#define IDC_STATICTEXT                  1107
#define IDC_LOOP                        1108
#define IDC_REMOVE                      1110
#define IDC_QUERY                       1111
#define IDC_SWITCH                      1112
#define IDC_XMLSELECTIONARG             1113
#define IDC_XMLSCOPEARG                 1114
#define IDC_DECENDING                   1115
#define IDC_XMLEXPLISITARG              1115
#define IDC_ACCESSCOMMAND               1116
#define IDC_XMLCOMMANDARG               1117
#define IDC_ACCESSVARIABLE              1118
#define IDC_ACENDING                    1120
#define IDC_SELECTION                   1120
#define IDC_SUGGESTION                  1121
#define IDC_ADDSELECTED                 1122
#define IDC_ADDSUGGESTED                1123
#define IDC_FINAL                       1125
#define IDC_SELECTTITLE                 1126
#define IDC_SUGGESTTITLE                1127
#define IDC_FINALTITLE                  1128
#define ID_RUN                          1130
#define IDC_QUERYRESULTS                1130
#define ID_STEP                         1131
#define ID_SUSPEND                      1132
#define ID_CONTINUE                     1133
#define IDC_REPORT                      1138
#define IDC_DORMANTSELECTION            1140
#define IDC_RUNDORMANT                  1141
#define IDC_DORMANTTITLE                1142
#define IDC_DORMANTLEFTTITLE            1146
#define IDC_FUNCTIONSLIDER              1148
#define IDC_FUNCTIONEDIT                1149
#define IDC_DATASLIDER                  1150
#define IDC_DATAEDIT                    1151
#define IDC_INSTANCESLIDER              1152
#define IDC_INSTANCEEDIT                1153
#define IDC_ARGUMENTSLIDER              1154
#define IDC_ARGUMENTEDIT                1155
#define IDC_RETURNSLIDER                1156
#define IDC_RETURNEDIT                  1157
#define IDC_CONTAINSLIDER               1158
#define IDC_CONTAINEDIT                 1159
#define IDC_FRIENDSLIDER                1160
#define IDC_FRIENDEDIT                  1161
#define IDC_SUBCLASSSLIDER              1162
#define IDC_SUBCLASSEDIT                1163
#define IDC_FILESLIDER                  1164
#define IDC_FILEEDIT                    1165
#define IDC_LOGICALSLIDER               1166
#define IDC_LOGICALEDIT                 1167
#define IDC_MEMBERSLIDER                1168
#define IDC_TRESHOLDSLIDER              1169
#define IDC_IGNORERADIO                 1170
#define IDC_EXCLUDERADIO                1171
#define IDC_ADDRADIO                    1172
#define IDC_FILENAMEEDIT                1174
#define IDC_LOGNAMEEDIT                 1175
#define IDC_RUNBUTTON                   1176
#define IDC_FUNCTIONTITLE               1177
#define IDC_DATATITLE                   1178
#define IDC_INSTANCETITLE               1179
#define IDC_ARGUMENTTITLE               1180
#define IDC_RETURNTITLE                 1181
#define IDC_CONTAINTITLE                1182
#define IDC_FRIENDTITLE                 1183
#define IDC_SUBCLASSTITLE               1184
#define IDC_FILETITLE                   1185
#define IDC_LOGICALTITLE                1186
#define IDC_FILENAMETITLE               1188
#define IDC_LOGNAMETITLE                1189
#define IDC_THRESHOLDTITLE              1190
#define IDC_MEMBERTITLE                 1192
#define IDC_MEMBEREDIT                  1193
#define IDC_THRESHOLDEDIT               1194
#define IDC_QATREE                      1202
#define IDC_QATREETITLE                 1203
#define IDC_RESET                       1208
#define IDC_SCOPE                       1209
#define IDC_REPORTER                    1210
#define IDC_SCOPETITLE                  1211
#define IDC_PROPERTIESTITLE             1212
#define IDC_SERVICECHANGED              1215
#define IDC_SERVICELIST                 1215
#define IDC_PREVCMD                     1218
#define IDC_NEXTCMD                     1219
#define IDC_STOP                        1220
#define IDC_COPYSEL                     1221
#define IDC_PASTESEL                    1222
#define IDC_EDIT                        1223
#define IDC_RETURNPRESSED               1224
#define IDC_STATUSCHANGED               1225
#define IDC_SELECTOR                    1226
#define IDC_PRESET                      1227
#define IDC_COMPTITLE                   1228
#define IDC_CHECKTITLE                  1233
#define IDC_TREESELECTOR                1234
#define IDC_PROP                        1235
#define IDC_VIEWER                      1237
#define IDC_DATASOURCECTRL              1239
#define IDC_NAME                        1240
#define IDC_SUBSOURCE                   1240
#define IDC_USER                        1241
#define IDC_FONT                        1242
#define IDC_NEWTREE                     1242
#define IDC_DELTREE                     1243
#define IDC_EDIT1                       1243
#define IDC_HOSTNAME                    1243
#define IDC_SPACELEVEL                  1244
#define IDC_COMMENTS                    1244
#define IDC_HOSTPORT                    1244
#define IDC_SPACEROW                    1245
#define IDC_PASSWORD                    1245
#define IDC_SPACECOLUMN                 1246
#define IDC_ISSUEID                     1246
#define IDC_USERNAME                    1247
#define IDC_LINE1                       1248
#define IDC_LINE2                       1249
#define IDC_NAMEMATCH                   1254
#define IDC_FILEMATCH                   1255
#define IDC_SCOPESEL                    1257
#define IDC_SCOPEALL                    1258
#define IDC_LEFTTORIGHT                 1260
#define IDC_TOPTOBOTTOM                 1261
#define IDC_RIGHTTOLEFT                 1262
#define IDC_BOTTOMTOTOP                 1263
#define IDC_JUSTIFY_START               1264
#define IDC_JUSTIFY_CENTER              1265
#define IDC_JUSTIFY_END                 1266
#define IDC_ORTHOGONAL                  1267
#define IDC_MERGEROWS                   1268
#define IDC_VARSPACE                    1269
#define IDC_SPACENODENAME               1270
#define IDC_SPACELEVELNAME              1271
#define IDC_SPACENODE                   1272
#define IDC_NODERED                     1276
#define IDC_UNSELECTED                  1277
#define IDC_NODEGREEN                   1278
#define IDC_NODEBLUE                    1279
#define IDC_SELECTED                    1280
#define IDC_FOCUSED                     1281
#define IDC_BORDERCOLOR                 1284
#define IDC_BORDERRED                   1285
#define IDC_BORDERGREEN                 1286
#define IDC_BORDERBLUE                  1287
#define IDC_NODECOLOR                   1288
#define IDC_THICKNESS                   1289
#define IDC_EDGECOLOR                   1290
#define IDC_EDGERED                     1291
#define IDC_EDGEGREEN                   1292
#define IDC_EDGEBLUE                    1293
#define IDC_EDGEUNSELECTED              1294
#define IDC_EDGESELECTED                1295
#define IDC_EDGEFOCUSED                 1296
#define IDC_PUBLIC                      1297
#define IDC_PROTECTED                   1298
#define IDC_PRIVATE                     1299
#define IDC_PACKAGE_ACCESS              1300
#define IDC_ENABLE_CLASS_MEHTODS        1301
#define IDC_ENABLE_CLASS_PROPERTIES     1302
#define IDC_SORT_BY_NAME                1303
#define IDC_SORT_BY_ACCESS              1304
#define IDC_SHORT_NAMES                 1305
#define IDC_LONG_NAMES                  1306
#define IDC_MERGESAME                   1307
#define IDC_RELATIONCOMBO               1308
#define IDC_VISIBLE                     1309
#define IDC_STYLECOMBO                  1310
#define IDC_GREEN                       1311
#define IDC_RED                         1312
#define IDC_BLUE                        1313
#define IDC_THICKNESSCOMBO              1314
#define IDC_COLOR                       1315
#define IDC_FILELIST                    1316
#define IDC_OPTIONS                     1318
#define IDC_PROJECTTREECTRL1            1319
#define IDC_TAB1                        1320
#define IDC_QUERYRESULTSCTRL1           1321
#define IDC_GETLIST                     1322
#define IDC_RESULTS                     1323
#define IDC_MANUAL                      1323
#define IDC_FILTER                      1324
#define IDC_ENABLEQUERIES               1325
#define IDC_NEXT                        1326
#define ID_BTN1                         1329
#define ID_BTN2                         1330
#define IDC_MESSAGE                     1331
#define IDC_PREV                        1333
#define IDC_CATEGORIES                  1334
#define IDC_QUERIES                     1335
#define IDC_GROUPS                      1336
#define IDC_SELECTFILTER                1337
#define IDC_TARGET                      1338
#define IDC_RESETFILTER                 1339
#define IDC_TO_TARGET                   1339
#define IDC_SELECTSORT                  1340
#define IDC_TO_SOURCE                   1340
#define IDC_SELATTRIBUTES               1341
#define IDC_ADDELEMENTS                 1342
#define IDC_SAVEELEMENTS                1345
#define IDC_LIST                        1347
#define IDC_RICHEDIT1                   1348
#define IDC_FROM                        1351
#define IDC_FILTER_SPIN                 1355
#define IDC_hEADER_SPIN                 1356
#define IDC_FIXDATE_CHECK               1359
#define IDC_OPENDATE_CHECK              1360
#define IDC_SEVERITY_CHECK              1361
#define IDC_ASSIGNEE_CHECK              1362
#define IDC_REPORTEDBY_CHECK            1363
#define IDC_UNRESTRICTED                1364
#define IDC_STATUS_CHECK                1365
#define IDC_ENTITIES_CHECK              1366
#define IDC_PRIORITY_CHECK              1367
#define IDC_BROWSE                      1368
#define IDC_FILENAME                    1369
#define IDC_TO                          1370
#define IDC_HEADER                      1371
#define IDC_BROWSER_CHECK               1372
#define IDC_CURSCOPE                    1373
#define IDC_BROWSERSELECTION            1374
#define IDC_GROUPSELECTION              1375
#define IDC_HTMLTYPE                    1377
#define IDC_SESSIONLIST                 1377
#define IDC_SESSIONNAME                 1378
#define IDC_CLOSURE                     1379
#define IDC_SHORTNAMES                  1380
#define IDC_DEVIATIONS                  1381
#define IDC_METRICS                     1383
#define IDC_CC_METRICS                  1384
#define IDC_CC_SPIN                     1385
#define IDC_SWITHCES_METRICS            1386
#define IDC_SWITHCES_SPIN               1387
#define IDC_SUBPROJECTS                 1388
#define IDC_VARIABLES                   1389
#define IDC_FUNCTIONS                   1390
#define IDC_MACROS                      1391
#define IDC_TEMPLATES                   1392
#define IDC_FILES                       1393
#define IDC_CLASSES                     1394
#define IDC_TYPEDEFS                    1395
#define IDC_UNIONS                      1396
#define IDC_ENUMERATIONS                1397
#define IDC_MODIFIED_FILES              1398
#define IDC_MODIFIED_PROJECTS           1399
#define IDC_NO_HIERARCHY                1400
#define IDC_CRITERIA                    1402
#define IDC_OUTPUT                      1404
#define IDC_QAERRORS                    1407
#define IDC_ERRORTYPE                   1408
#define IDC_ERRORS                      1409
#define IDC_ERRORSLOG                   1410
#define IDC_COMP                        1415
#define IDC_VAL                         1416
#define IDC_AUTOMATIC                   1419
#define IDC_MANUAL_HEADER               1421
#define IDC_AUTOMATIC_HEADER            1422
#define IDC_FILENAME_HEADER             1423
#define IDC_GET_HEADER                  1424
#define IDC_EXPLORER                    1426
#define IDC_CODEROVERINTEGRATORCTRL     1427
#define IDC_EDITORSELECTOR              1428
#define IDC_CMSELECTOR                  1429
#define IDC_CMINTEGRATORCTRL            1432
#define IDC_OKALL                       1439
#define IDC_BORDER                      1441
#define IDC_IMPACTCTRL                  1449
#define IDC_ABOUT_IMAGE                 1450
#define IDC_REPOSITORYNAME              1451
#define IDC_SELECTREPOSITORY            1452
#define IDC_STARTMODEL                  1453
#define IDC_STOPMODEL                   1454
#define IDC_BROWSEMODEL                 1455
#define IDC_CLOSEMANAGER                1456
#define IDC_REFRESHMODELS               1458
#define IDC_QUERIES_START               3000
#define ID_CM_ACTIONS                   20110
#define ID_CANCEL_EDIT_CNTR             32768
#define ID_CANCEL_EDIT_SRVR             32769
#define ID_REMOVEGROUP                  32773
#define ID_REMOVESELECTION              32774
#define ID_TPM                          32781
#define ID_MAKECLIENTS                  32782
#define ID_MODIFIED_ENTITIES            32783
#define ID_MAKESERVERS                  32784
#define ID_CHECKOUT                     32785
#define ID_MAKEPEERS                    32786
#define ID_CHECKIN                      32787
#define ID_MAKEUNRELATED                32788
#define ID_UNCHECKOUT                   32789
#define ID_LOCK                         32791
#define ID_CLOSE                        32792
#define ID_UNLOCK                       32793
#define ID_VIEW_ALLMEMBERS              32794
#define ID_HOMEPROJECT                  32795
#define ID_VIEW_PUBLICMEMBERS           32796
#define ID_PROJECTSCOPE                 32797
#define ID_VIEW_PRIVATEMEMBERS          32798
#define ID_PREFERENCES                  32799
#define ID_VIEW_CLIENTS                 32800
#define ID_VIEWTREE                     32801
#define ID_VIEW_SERVERS                 32802
#define ID_VIEWINHERITANCE              32803
#define ID_VIEW_PEERS                   32804
#define ID_VIEWERD                      32805
#define ID_VIEW_UNRELATED               32806
#define ID_VIEWDATACHART                32807
#define ID_VIEWOUTLINE                  32808
#define ID_VIEWFLOWCHART                32809
#define ID_VIEW_RELATIONS               32811
#define ID_DORMANT                      32812
#define ID_MAKEPRIVATE                  32815
#define ID_PACKAGE                      32816
#define ID_SIMPLIFY                     32817
#define ID_AUTODOC                      32818
#define ID_MAKEPUBLIC                   32819
#define ID_SUMMARY                      32820
#define ID_PRINTREPORT                  32821
#define D_WINDOW_CASCADE                32823
#define ID_UPDATE                       32824
#define ID_XMLREPORT                    32825
#define ID_MAKEXML                      32826
#define ID_XMLOPEN                      32827
#define ID_XMLSAVE                      32828
#define ID_PREVIEW                      32829
#define ID_SETTINGS                     32830
#define ID_XMLSETTINGS                  32831
#define ID_XMLPREVIEW                   32832
#define ID_XMLSAVEAS                    32833
#define ID_XMLNEW                       32834
#define ID_PREVIEWXML                   32835
#define ID_TREEDIAGRAM                  32848
#define ID_INHERITANCE                  32849
#define ID_ERD                          32851
#define ID_DATACHART                    32856
#define ID_FLOWCHART                    32858
#define ID_OUTLINE                      32859
#define ID_QA                           32865
#define ID_QARESET                      32867
#define ID_QARUN                        32868
#define ID_QARUNSEL                     32869
#define ID_QABROWSE                     32870
#define ID_SERVICESELECT                32871
#define ID_ACCESS                       32872
#define ID_OPENTREEDIAGRAM              32890
#define ID_OPENINHERITANCE              32891
#define ID_OPENERD                      32892
#define ID_OPENDATACHART                32893
#define ID_OPENOUTLINE                  32894
#define ID_OPENFLOWCHART                32895
#define ID_SHOWATTRIBUTES               32897
#define ID_SHOWOPERATIONS               32899
#define ID_BUILDRELATIONS               32900
#define ID_OTHERRELATIONS               32901
#define ID_MEMBERS                      32902
#define ID_ADDCLASS                     32905
#define ID_REMOVECLASS                  32906
#define ID_ARGUMENTS                    32907
#define ID_PRUNE                        32908
#define IDC_GRAPHPROP                   32918
#define ID_BUTTON32919                  32919
#define ID_VIEW_BROWSER                 32923
#define ID_VIEW_GRAPHBAR                32924
#define IDC_SIMPLIFY                    32925
#define ID_NEWSUBTREE                   32932
#define ID_CALLGRAPH                    32937
#define ID_INCLUSION                    32940
#define ID_SIMPLIFY_UPDATE              32941
#define ID_SIMPLIFY_PREV                32942
#define ID_SIMPLIFY_NEXT                32943
#define ID_QASAVE                       32947
#define ID_QAOPEN                       32948
#define IDC_VIEW_ERRORS                 32949
#define IDC_SAVEREPORT                  32958
#define IDC_IMATTACHMENT                32959
#define ID_EDITOR_SETUP                 32966
#define ID_CM_SETUP                     32967
#define IDC_IMPACT                      32969
#define ID_IMATTACHMENT                 32970
#define GRAPH_CONTAINS_INSTANCE_OF      34436
#define GRAPH_CONTAINED_IN              34437
#define GRAPH_POINTS_TO                 34438
#define GRAPH_HAVE_ARGUMENTS            34439

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        386
#define _APS_NEXT_COMMAND_VALUE         32971
#define _APS_NEXT_CONTROL_VALUE         1459
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
