// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSpreadsheet wrapper class

class CSpreadsheet : public CWnd
{
protected:
	DECLARE_DYNCREATE(CSpreadsheet)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xfc470417, 0x2bf8, 0x11d2, { 0xaf, 0x3, 0x0, 0xa0, 0xc9, 0xb7, 0x1d, 0xc4 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	long GetRows();
	void SetRows(long);
	long GetCols();
	void SetCols(long);
	long GetFixedRows();
	void SetFixedRows(long);
	long GetFixedCols();
	void SetFixedCols(long);
	short GetUserSelection();
	void SetUserSelection(short);
	long GetCurrentRow();
	void SetCurrentRow(long);
	long GetCurrentColumn();
	void SetCurrentColumn(long);
	BOOL GetEnableDraw();
	void SetEnableDraw(BOOL);

// Operations
public:
	short GetCellType(long row, long col);
	void SetCellType(long row, long col, short nNewValue);
	CString GetCellText(long row, long col);
	void SetCellText(long row, long col, LPCTSTR lpszNewValue);
	void AddMenuItem(long row, long col, LPCTSTR text);
	BOOL GetCellCheck(long row, long col);
	void SetCellCheck(long row, long col, BOOL bNewValue);
	void AddRow(long after);
	void RemoveRow(long row);
	long GetColWidth(long col);
	void SetColWidth(long col, long nNewValue);
	void Clear();
	void AboutBox();
};
